"""Create initial user db, with one table: user

Revision ID: 344c31f29b36
Revises: None
Create Date: 2015-09-03 12:31:08.820088

"""

# revision identifiers, used by Alembic.
revision = '344c31f29b36'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('reg_key', sa.String(length=80), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('registered', sa.Boolean(), nullable=True),
    sa.Column('csrf', sa.String(length=80), nullable=True),
    sa.Column('password_digest', sa.String(length=200), nullable=True),
    sa.Column('role', sa.Enum('admin', 'user', 'public', name='role'), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
